---
abstract: 'Filter history by type on ticket display page'
author:
  - 'Christian Loos <cloos@netsandbox.de>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-HistoryFilter
no_index:
  directory:
    - etc
    - html
    - inc
  package:
    - RT::Transaction
requires:
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/cloos/RT-Extension-HistoryFilter
version: 1.01
x_module_install_rtx_version: 0.35
x_requires_rt: 4.0.0
x_rt_too_new: 4.4.0
